# Generated by Django 5.1.3 on 2025-01-12 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0004_task_users_task_assignment_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
    ]
